# Generated by Django 4.2.4 on 2023-09-24 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_version'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('name', 'category', 'price', 'modification_date'), 'permissions': [('can_change_product', 'Can change product')], 'verbose_name': 'программный продукт', 'verbose_name_plural': 'программные продукты'},
        ),
        migrations.AddField(
            model_name='product',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Признак публикации'),
        ),
        migrations.AddField(
            model_name='product',
            name='user',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Создатель'),
        ),
    ]
